spring:

  application:
    name: codecore-api

  profiles:
    active: local

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db_codecore
    username: codecore
    password: codecore0803861400

  flyway:
    url: jdbc:postgresql://localhost:5432/db_codecore
    user: codecore
    password: codecore0803861400

server:
  port: 8080

management:

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always