-- =============================================================================
-- V2 — IAM User (multi-tenant authentication identity)
-- Schema: iam (V1)
-- PostgreSQL 16+
-- =============================================================================
-- First persistent entity. Maps to domain aggregate Identity (iam_user naming
-- avoids reserved word "user" and SQL keyword collisions.
-- =============================================================================

CREATE TABLE iam.iam_user (
    id                  UUID                     NOT NULL,
    tenant_id           UUID                     NOT NULL,
    email               VARCHAR(320)             NOT NULL,
    normalized_email    VARCHAR(320)             NOT NULL,
    password_hash       VARCHAR(500)             NOT NULL,
    first_name          VARCHAR(150),
    last_name           VARCHAR(150),
    status              VARCHAR(50)              NOT NULL,
    email_verified      BOOLEAN                  NOT NULL DEFAULT FALSE,
    last_login_at       TIMESTAMPTZ,
    created_at          TIMESTAMPTZ              NOT NULL,
    updated_at          TIMESTAMPTZ              NOT NULL,
    version             BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT pk_iam_user
        PRIMARY KEY (id),

    CONSTRAINT uq_iam_user_tenant_normalized_email
        UNIQUE (tenant_id, normalized_email),

    CONSTRAINT ck_iam_user_status
        CHECK (status IN (
            'ACTIVE',
            'LOCKED',
            'DISABLED',
            'PENDING_VERIFICATION',
            'PASSWORD_RESET_REQUIRED'
        )),

    CONSTRAINT ck_iam_user_email_not_blank
        CHECK (char_length(trim(email)) > 0),

    CONSTRAINT ck_iam_user_normalized_email_not_blank
        CHECK (char_length(trim(normalized_email)) > 0),

    CONSTRAINT ck_iam_user_version_non_negative
        CHECK (version >= 0)
);

COMMENT ON TABLE iam.iam_user IS
    'Tenant-scoped IAM identity for credential-based authentication.';

COMMENT ON COLUMN iam.iam_user.id IS
    'Surrogate primary key (domain IdentityId). Generated by application.';

COMMENT ON COLUMN iam.iam_user.tenant_id IS
    'Tenant isolation key; all queries MUST filter by tenant_id.';

COMMENT ON COLUMN iam.iam_user.email IS
    'Display/login email as entered by the user (case preserved).';

COMMENT ON COLUMN iam.iam_user.normalized_email IS
    'Canonical email for uniqueness and lookup (typically lowercased/trimmed).';

COMMENT ON COLUMN iam.iam_user.password_hash IS
    'One-way password digest (e.g. Argon2id/bcrypt); never store plaintext.';

COMMENT ON COLUMN iam.iam_user.status IS
    'Lifecycle state aligned with IdentityStatus enum in domain layer.';

COMMENT ON COLUMN iam.iam_user.version IS
    'Optimistic locking counter for concurrent updates.';

-- Tenant-scoped lookups and admin filters
CREATE INDEX idx_iam_user_tenant_id
    ON iam.iam_user (tenant_id);

CREATE INDEX idx_iam_user_email
    ON iam.iam_user (email);

CREATE INDEX idx_iam_user_normalized_email
    ON iam.iam_user (normalized_email);

CREATE INDEX idx_iam_user_status
    ON iam.iam_user (status);
